site_name: My site
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
plugins:
  - search

nav:
  - 主页:
    - "index.md"
  - 高考:
    - "Gaokao/index.md"
    - 语文: 
      - "Gaokao/Chinese/essay.md"
    - 数学:
      - 概率统计:
        - 马尔可夫链: "Gaokao/Math/PS/Markov_chain.md"
        - 概率递推: "Gaokao/Math/PS/Recursion.md"
        - 调整法: "Gaokao/Math/PS/Adjustment_method.md"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/katex@0/dist/katex.min.css