site_name: My site
theme: 
  name: material
  features:
    - navigation.tabs
plugins:
  - search

nav:
  - 主页:
    - "index.md"
  - 高考:
    - "Gaokao/index.md"
    - 语文: 
      - "Gaokao/Chinese/essay.md"

