site_name: My site
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
plugins:
  - search

nav:
  - 主页:
    - "index.md"
  - 高考:
    - "Gaokao/index.md"
    - 语文: 
      - "Gaokao/Chinese/essay.md"
    - 数学:
      - 概率统计:
        - 马尔可夫链: "Gaokao/Math/PS/Markov chain.md"

